### ISSUE TITLE
Table of contents: add button to close outline from itself

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#2904]
**Describe the bug**
The table of contents can only be opened and closed by navigating to the headings submenu in the menubar. While this is fine for opening the outline, it feels quite cumbersome for closing it. We should add a button to the outline view to close it from itself.

**Comment by mejo-** [comment]
@vinicius73

**Comment by mejo-** [comment]
Sorry, I only tested the outline on Collectives and there the heading and close button were hidden by the menubar. I fixed this now by adding the following in Collectives:

```scss
[data-text-el='editor-container'] .editor--outline {
	z-index: 10021;
}
```
