### ISSUE TITLE
Too much extra spacing

### ISSUE THREAD

**Issue by nickian** [nextcloud/text#619]
NextCloud v18.0
Text v2.0.0

Is it just me, or is there way too much extra spacing below the editor/markdown preview?

In order to tighten it up to look normal, I had to install the custom CSS plugin and add this:

```
#editor {
    height: auto !important;
    padding-bottom: 25px !important;
}
```

**Comment by juliushaertl** [comment]
Could you maybe show a screenshot to show which view you are actually referring to? Maybe also one that shows the difference with your change?

**Comment by nickian** [comment]
Sure. I just think it's odd that the file list starts at 50% of the bottom of the page instead of simply being below the markdown text.

<img width="1599" alt="Screen Shot 2020-02-05 at 12 56 18 PM" src="https://user-images.githubusercontent.com/590678/73878005-fd0a1c00-4816-11ea-9589-326b5c479f7c.png">

Which is the result of this: 

```css
#rich-workspace[data-v-6213c251] #editor {
    padding-bottom: 80px;
    overflow: scroll !important;
    height: 50vh;
}
```

vs something more like this:

<img width="1754" alt="Screen Shot 2020-02-05 at 12 59 07 PM" src="https://user-images.githubusercontent.com/590678/73878212-68ec8480-4817-11ea-89eb-ec6df6686590.png">
