### ISSUE TITLE
Only trigger asset builds on merges and l10n pushes

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#6803]
Right now we trigger the `update-node-dist` workflow on all pushes to the integration branches.
If the build changes files we push a new commit. If it does not we're done.

This has two downsides:
* Every merge triggers two runs. One that does the actual build and pushes a commit and then the one that is triggered by that commit. We don' t actually need the latter.
* If we ever create a non-deterministic build we will get an endless loop of `update-node-dist` runs that push their changes and create new `update-node-dist` runs.

@mejo- propose:
> I wonder whether something like https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request_target-workflow-when-a-pull-request-merges would be better.

However we also need to rebuild the js assets after the transifex changes have been pushed and they are pushed directly to master.

Maybe we could do something like this:

```yaml
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
      - stable30
      - stable29
      - stable28
  push:
    paths:
      - l10n
    branches:
      - main
      - stable30
      - stable29
      - stable28

```

_Originally posted by @max-nextcloud in https://github.com/nextcloud/text/issues/6801#issuecomment-2554024922_
